
auth.token=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

defaults.org=madebyryan
defaults.project=react-native-winnergpt

defaults.url=https://sentry.io/
